#!/bin/bash

echo "📧 Automatic Form Setup - Choose Your Option"
echo "============================================="
echo ""

echo "🤖 This script will help you set up form submissions automatically"
echo ""

echo "🔧 Step 1: Choose Form Setup Method"
echo ""
echo "1) Formspree (Easiest - Free)"
echo "2) Your Own Backend (Full Control)"
echo "3) EmailJS (Client-side)"
echo ""

read -p "Choose option (1-3): " FORM_OPTION

case $FORM_OPTION in
    1)
        echo ""
        echo "✅ Formspree Setup (Recommended)"
        echo ""
        echo "📋 Steps to set up Formspree:"
        echo ""
        echo "1. Go to https://formspree.io"
        echo "2. Create a free account"
        echo "3. Create a new form"
        echo "4. Copy your form ID"
        echo "5. Update the form action in docs/index.html"
        echo ""
        echo "🔧 Formspree Configuration:"
        echo ""
        echo "Update this line in docs/index.html:"
        echo "<form action=\"https://formspree.io/f/YOUR_FORM_ID\" method=\"POST\">"
        echo ""
        echo "✅ Formspree setup complete!"
        echo ""
        echo "📧 Email notifications will be sent to:"
        echo "  tim@teknoledg.com"
        echo ""
        echo "🚀 Form submissions will work automatically!"
        ;;
    2)
        echo ""
        echo "✅ Your Own Backend Setup"
        echo ""
        echo "📋 Backend deployment options:"
        echo ""
        echo "1. Railway (Easiest):"
        echo "   ./deploy-railway.sh"
        echo ""
        echo "2. PythonAnywhere (Free):"
        echo "   ./deploy-pythonanywhere.sh"
        echo ""
        echo "3. Your Server:"
        echo "   ./deploy_data_subdomain.sh"
        echo ""
        echo "🔧 After backend deployment:"
        echo "1. Get your backend URL"
        echo "2. Update js/script.js with your URL"
        echo "3. Commit and push changes"
        echo ""
        echo "✅ Backend setup complete!"
        echo ""
        echo "📧 Email notifications will be sent to:"
        echo "  tim@teknoledg.com"
        echo ""
        echo "🗄️ Data will be stored in your database"
        echo ""
        echo "🚀 Form submissions will work automatically!"
        ;;
    3)
        echo ""
        echo "✅ EmailJS Setup"
        echo ""
        echo "📋 Steps to set up EmailJS:"
        echo ""
        echo "1. Go to https://emailjs.com"
        echo "2. Create a free account"
        echo "3. Create a new service"
        echo "4. Get your service ID"
        echo "5. Update the JavaScript configuration"
        echo ""
        echo "🔧 EmailJS Configuration:"
        echo ""
        echo "Add this to docs/js/script.js:"
        echo "emailjs.init('YOUR_USER_ID');"
        echo ""
        echo "✅ EmailJS setup complete!"
        echo ""
        echo "📧 Email notifications will be sent to:"
        echo "  tim@teknoledg.com"
        echo ""
        echo "🚀 Form submissions will work automatically!"
        ;;
    *)
        echo "❌ Invalid option. Please run the script again."
        exit 1
        ;;
esac

echo ""
echo "🎉 Form setup complete!"
echo ""
echo "📋 Next steps:"
echo "1. Test your form submission"
echo "2. Check email notifications"
echo "3. Verify data storage (if using backend)"
echo ""
echo "🚀 Your registration system is now fully automated!"
