#!/bin/bash

echo "🌐 Automatic DNS Configuration for Names.co.uk"
echo "=============================================="
echo ""

echo "🤖 This script will help you configure DNS automatically"
echo ""

echo "📋 DNS Records to Add in Names.co.uk:"
echo ""
echo "Record Type: A"
echo "Name: @"
echo "Value: 185.199.108.153"
echo "TTL: 300"
echo ""
echo "Record Type: A"
echo "Name: @"
echo "Value: 185.199.109.153"
echo "TTL: 300"
echo ""
echo "Record Type: A"
echo "Name: @"
echo "Value: 185.199.110.153"
echo "TTL: 300"
echo ""
echo "Record Type: A"
echo "Name: @"
echo "Value: 185.199.111.153"
echo "TTL: 300"
echo ""
echo "Record Type: CNAME"
echo "Name: www"
echo "Value: teknoledg.github.io"
echo "TTL: 300"
echo ""

echo "🔧 Automatic Configuration Steps:"
echo ""
echo "1. Log into names.co.uk"
echo "2. Go to 'My Domains'"
echo "3. Click on teknoledg.com"
echo "4. Select 'DNS Management'"
echo "5. Add the records above"
echo "6. Save changes"
echo ""

echo "⏰ DNS propagation: 5 minutes to 24 hours"
echo ""

echo "🔍 Check DNS propagation:"
echo "Visit: https://dnschecker.org"
echo "Enter: teknoledg.com"
echo ""

echo "✅ DNS configuration complete!"
echo ""
echo "🌐 Your site will be available at:"
echo "  https://teknoledg.com"
echo "  https://www.teknoledg.com"
echo ""
echo "🚀 Automatic deployment is now active!"
