#!/bin/bash

echo "🌐 Names.co.uk Domain Configuration Script"
echo "=========================================="
echo ""

echo "📋 This script will help you configure your domain with names.co.uk"
echo ""

echo "🔧 Step 1: Choose Your Setup"
echo ""
echo "1) GitHub Pages + Your Server (Recommended)"
echo "2) Everything on Your Server"
echo "3) Subdomain Setup"
echo ""

read -p "Choose option (1-3): " SETUP_OPTION

case $SETUP_OPTION in
    1)
        echo ""
        echo "✅ GitHub Pages + Your Server Setup"
        echo ""
        echo "📋 DNS Records to add in names.co.uk:"
        echo ""
        echo "Record Type: A"
        echo "Name: @"
        echo "Value: 185.199.108.153"
        echo "TTL: 300"
        echo ""
        echo "Record Type: A"
        echo "Name: @"
        echo "Value: 185.199.109.153"
        echo "TTL: 300"
        echo ""
        echo "Record Type: A"
        echo "Name: @"
        echo "Value: 185.199.110.153"
        echo "TTL: 300"
        echo ""
        echo "Record Type: A"
        echo "Name: @"
        echo "Value: 185.199.111.153"
        echo "TTL: 300"
        echo ""
        echo "Record Type: CNAME"
        echo "Name: www"
        echo "Value: teknoledg.github.io"
        echo "TTL: 300"
        echo ""
        echo "Record Type: A"
        echo "Name: api"
        echo "Value: YOUR_SERVER_IP"
        echo "TTL: 300"
        echo ""
        echo "🚀 Next steps:"
        echo "1. Add these DNS records in names.co.uk"
        echo "2. Deploy frontend to GitHub Pages"
        echo "3. Deploy backend to your server"
        echo "4. Update frontend to use your backend URL"
        ;;
    2)
        echo ""
        echo "✅ Everything on Your Server Setup"
        echo ""
        read -p "Enter your server IP address: " SERVER_IP
        echo ""
        echo "📋 DNS Records to add in names.co.uk:"
        echo ""
        echo "Record Type: A"
        echo "Name: @"
        echo "Value: $SERVER_IP"
        echo "TTL: 300"
        echo ""
        echo "Record Type: A"
        echo "Name: www"
        echo "Value: $SERVER_IP"
        echo "TTL: 300"
        echo ""
        echo "Record Type: A"
        echo "Name: api"
        echo "Value: $SERVER_IP"
        echo "TTL: 300"
        echo ""
        echo "🚀 Next steps:"
        echo "1. Add these DNS records in names.co.uk"
        echo "2. Deploy everything to your server"
        echo "3. Configure SSL certificates"
        echo "4. Test the application"
        ;;
    3)
        echo ""
        echo "✅ Subdomain Setup"
        echo ""
        read -p "Enter your server IP address: " SERVER_IP
        echo ""
        echo "📋 DNS Records to add in names.co.uk:"
        echo ""
        echo "Record Type: A"
        echo "Name: @"
        echo "Value: $SERVER_IP"
        echo "TTL: 300"
        echo ""
        echo "Record Type: A"
        echo "Name: www"
        echo "Value: $SERVER_IP"
        echo "TTL: 300"
        echo ""
        echo "Record Type: A"
        echo "Name: api"
        echo "Value: $SERVER_IP"
        echo "TTL: 300"
        echo ""
        echo "🚀 Next steps:"
        echo "1. Add these DNS records in names.co.uk"
        echo "2. Deploy frontend to teknoledg.com"
        echo "3. Deploy backend to api.teknoledg.com"
        echo "4. Configure SSL certificates"
        ;;
    *)
        echo "❌ Invalid option. Please run the script again."
        exit 1
        ;;
esac

echo ""
echo "📝 Instructions for names.co.uk:"
echo ""
echo "1. Log into your names.co.uk account"
echo "2. Go to 'My Domains'"
echo "3. Click on teknoledg.com"
echo "4. Select 'DNS Management' or 'Advanced DNS'"
echo "5. Add the DNS records shown above"
echo "6. Save changes"
echo ""
echo "⏰ DNS propagation can take up to 24 hours"
echo ""

echo "🔍 To check DNS propagation:"
echo "Visit: https://dnschecker.org"
echo "Enter: teknoledg.com"
echo ""

echo "✅ Configuration complete!"
echo ""
echo "📞 If you need help with names.co.uk:"
echo "- Check their support documentation"
echo "- Contact their support team"
echo "- Use their live chat feature"
