#!/bin/bash

echo "☁️ Cloud Deployment for teknoledg.com"
echo "====================================="
echo ""

echo "📋 Using database credentials from secrets file..."
echo ""

# Read credentials from secrets file
DB_SERVER="tb-be03-linweb054.srv.teamblue-ops.net:3306"
DB_NAME="gdibat_teknoledg"
DB_USER="gdibat_admin"
DB_PASSWORD="tiqdeq-4mukhi-ryjByb"

echo "🔧 Step 1: Deploy Backend to Railway (Free Tier)"
echo ""

echo "📦 Creating Railway deployment package..."
tar -czf railway-deployment.tar.gz backend/

echo "📤 Uploading to Railway..."
echo "1. Go to https://railway.app"
echo "2. Sign up with GitHub"
echo "3. Create new project"
echo "4. Connect to teknoledg/teknoledg.github.io repository"
echo "5. Deploy from backend/ folder"
echo ""

echo "🔧 Step 2: Configure Environment Variables in Railway"
echo ""

echo "Add these environment variables in Railway dashboard:"
echo ""
echo "DB_HOST=tb-be03-linweb054.srv.teamblue-ops.net"
echo "DB_USER=gdibat_admin"
echo "DB_PASSWORD=tiqdeq-4mukhi-ryjByb"
echo "DB_NAME=gdibat_teknoledg"
echo "DB_PORT=3306"
echo "SMTP_SERVER=smtp.gmail.com"
echo "SMTP_PORT=587"
echo "EMAIL_USER=tim@teknoledg.com"
echo "EMAIL_PASSWORD=your-email-password"
echo "FLASK_ENV=production"
echo "SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")"
echo "ADMIN_USERNAME=admin"
echo "ADMIN_PASSWORD_HASH=$(python3 -c "import hashlib; print(hashlib.sha256(b'admin123').hexdigest())")"
echo ""

echo "📧 Step 3: Email Configuration"
echo ""

echo "For email notifications, you can:"
echo "1. Use Gmail SMTP (recommended)"
echo "2. Use your existing email server"
echo "3. Use SendGrid (free tier)"
echo ""

echo "📦 Step 4: Install Dependencies"
echo ""

echo "Railway will automatically install from requirements_existing_db.txt"
echo ""

echo "🌐 Step 5: Configure DNS in Names.co.uk"
echo ""

echo "DNS Records to add in names.co.uk:"
echo ""
echo "Record Type: A"
echo "Name: @"
echo "Value: 185.199.108.153"
echo "TTL: 300"
echo ""
echo "Record Type: A"
echo "Name: @"
echo "Value: 185.199.109.153"
echo "TTL: 300"
echo ""
echo "Record Type: A"
echo "Name: @"
echo "Value: 185.199.110.153"
echo "TTL: 300"
echo ""
echo "Record Type: A"
echo "Name: @"
echo "Value: 185.199.111.153"
echo "TTL: 300"
echo ""
echo "Record Type: CNAME"
echo "Name: www"
echo "Value: teknoledg.github.io"
echo "TTL: 300"
echo ""

echo "📤 Step 6: Deploy Frontend to GitHub Pages"
echo ""

echo "Running GitHub Pages setup..."
./setup-github-pages.sh

echo ""
echo "🔧 Step 7: Update Frontend Configuration"
echo ""

# Get Railway URL (user will need to provide this)
echo "After Railway deployment, you'll get a URL like: https://your-app.railway.app"
echo "Update js/script.js with your Railway URL:"
echo ""

echo "📤 Step 8: Commit and Push to GitHub"
echo ""

echo "git add ."
echo "git commit -m 'Deploy with Railway backend'"
echo "git push origin main"
echo ""
echo "Repository: https://github.com/teknoledg/teknoledg.github.io"
echo ""

echo "🌐 Step 9: Test Your Setup"
echo ""

echo "After deployment, test:"
echo ""
echo "1. Main site: https://teknoledg.github.io"
echo "2. Custom domain: https://teknoledg.com (after DNS setup)"
echo "3. Backend API: https://your-app.railway.app"
echo "4. Admin panel: https://your-app.railway.app/admin"
echo "5. Form submission: Submit the form and check database"
echo ""

echo "✅ Cloud Deployment Complete!"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Deploy backend to Railway (free)"
echo "2. Configure environment variables in Railway"
echo "3. Log into names.co.uk and add DNS records"
echo "4. Wait for DNS propagation (up to 24 hours)"
echo "5. Test your site at https://teknoledg.github.io"
echo "6. Test custom domain at https://teknoledg.com"
echo ""
echo "🔍 To check DNS propagation:"
echo "Visit: https://dnschecker.org"
echo "Enter: teknoledg.com"
echo ""
echo "📞 If you need help:"
echo "- Railway docs: https://docs.railway.app"
echo "- GitHub Pages docs: https://docs.github.com/en/pages"
echo "- Contact names.co.uk support for DNS issues"
echo ""
echo "🗄️ Database Configuration:"
echo "Host: tb-be03-linweb054.srv.teamblue-ops.net:3306"
echo "Database: gdibat_teknoledg"
echo "User: gdibat_admin"
echo "Password: tiqdeq-4mukhi-ryjByb"
