#!/bin/bash

echo "🚀 Deploying to PythonAnywhere (Free tier)"
echo ""

echo "📋 Manual deployment steps for PythonAnywhere:"
echo ""
echo "1. 🌐 Go to https://www.pythonanywhere.com"
echo "2. 📝 Create a free account"
echo "3. 📁 Upload your backend files to your home directory"
echo "4. ⚙️ Configure your web app:"
echo "   - Source code: /home/yourusername/backend"
echo "   - Working directory: /home/yourusername/backend"
echo "   - WSGI file: /var/www/yourusername_pythonanywhere_com_wsgi.py"
echo ""
echo "5. 📄 Create WSGI file:"
echo "   Add this to your WSGI file:"
echo ""
echo "   import sys"
echo "   path = '/home/yourusername/backend'"
echo "   if path not in sys.path:"
echo "       sys.path.append(path)"
echo ""
echo "   from app import app as application"
echo ""
echo "6. 🔧 Set environment variables in PythonAnywhere:"
echo "   - EMAIL_PASSWORD=your_email_password"
echo "   - ADMIN_USERNAME=admin"
echo "   - ADMIN_PASSWORD_HASH=$(python3 -c 'import hashlib; print(hashlib.sha256(b\"your_password\").hexdigest())')"
echo ""
echo "7. 🚀 Reload your web app"
echo ""
echo "✅ Your backend will be available at:"
echo "   https://yourusername.pythonanywhere.com"
echo ""
echo "📧 Admin panel:"
echo "   https://yourusername.pythonanywhere.com/admin"
