#!/bin/bash

echo "🔧 Manual Deployment Steps"
echo "========================="
echo ""

echo "1. First, accept the SSH host key:"
echo "   ssh gdibatb-hostingcom@gdibat.ssh.tb-hosting.com"
echo "   (Type 'yes' when prompted)"
echo ""

echo "2. Upload the backend files:"
echo "   scp -r backend/ gdibatb-hostingcom@gdibat.ssh.tb-hosting.com:/var/www/teknoledg-api/"
echo ""

echo "3. Create environment file on server:"
echo "   ssh gdibatb-hostingcom@gdibat.ssh.tb-hosting.com"
echo "   cd /var/www/teknoledg-api"
echo "   cat > .env << 'EOF'"
echo "DB_HOST=tb-be03-linweb054.srv.teamblue-ops.net"
echo "DB_USER=gdibat_admin"
echo "DB_PASSWORD=tiqdeq-4mukhi-ryjByb"
echo "DB_NAME=gdibat_teknoledg"
echo "DB_PORT=3306"
echo "SMTP_SERVER=smtp.gmail.com"
echo "SMTP_PORT=587"
echo "EMAIL_USER=hello@thepersonaldataexchange.com"
echo "EMAIL_PASSWORD=your-gmail-app-password"
echo "FLASK_ENV=production"
echo "SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")"
echo "ADMIN_USERNAME=admin"
echo "ADMIN_PASSWORD_HASH=$(python3 -c "import hashlib; print(hashlib.sha256(b'admin123').hexdigest())")"
echo "EOF"
echo ""

echo "4. Install dependencies:"
echo "   pip3 install -r requirements_existing_db.txt"
echo ""

echo "5. Run the application:"
echo "   python3 app_existing_db.py"
echo ""

echo "6. Deploy frontend to GitHub:"
echo "   git add ."
echo "   git commit -m 'Deploy to GitHub Pages'"
echo "   git push origin main"
echo ""

echo "7. Configure DNS in names.co.uk:"
echo "   - Add A record for 'data' pointing to your server IP"
echo "   - Add A records for '@' pointing to GitHub Pages IPs"
echo "   - Add CNAME for 'www' pointing to teknoledg.github.io"
echo ""

echo "✅ After these steps, your site will be live!"
echo "   Frontend: https://teknoledg.github.io"
echo "   Backend: https://data.teknoledg.com"
echo "   Admin: https://data.teknoledg.com/admin"
