#!/bin/bash

echo "🚀 Starting Backend Service"
echo "========================="
echo ""

echo "Once Python is installed on your server, run these commands:"
echo ""
echo "1. Connect to your server:"
echo "   ssh gdibatb-hostingcom@gdibat.ssh.tb-hosting.com"
echo ""
echo "2. Navigate to the backend directory:"
echo "   cd ~/teknoledg-api"
echo ""
echo "3. Install Python dependencies:"
echo "   pip3 install -r requirements_existing_db.txt"
echo ""
echo "4. Start the backend service:"
echo "   python3 app_existing_db.py"
echo ""
echo "5. Test the backend API:"
echo "   curl https://data.teknoledg.com"
echo ""
echo "6. Test the admin panel:"
echo "   Open: https://data.teknoledg.com/admin"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
echo "✅ Your backend will be running at:"
echo "   https://data.teknoledg.com"
echo "   https://data.teknoledg.com/admin"
echo ""
echo "📧 Email notifications will be sent to:"
echo "   hello@thepersonaldataexchange.com"
